apiVersion: v1
kind: Service
metadata:
  name: sptr-backend
  labels:
    {{- include "sptr-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sptr-backend.selectorLabels" . | nindent 4 }}
